export default {
  CHANGE_DIMENSIONS: 'CHANGE_DIMENSIONS',
  SET_CITY: 'SET_CITY',
  IS_NAV_SHOW: 'IS_NAV_SHOW',
  SET_NAV_HEIGHT: 'SET_NAV_HEIGHT',
  MODAL_APPOINTMENT_OPEN: 'MODAL_APPOINTMENT_OPEN',
  MODAL_NONRESIDENT_OPEN: 'MODAL_NONRESIDENT_OPEN',
  MODAL_QUESTION_OPEN: 'MODAL_QUESTION_OPEN',
  MODAL_REVIEW_OPEN: 'MODAL_REVIEW_OPEN',
  IS_MOB_NAV_SHOW: 'IS_MOB_NAV_SHOW'
};
